#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Jul 28, 2019 08:53:02 PM CDT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import formMain_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    formMain_support.set_Tk_var()
    top = Toplevel1 (root)
    formMain_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    rt = root
    w = tk.Toplevel (root)
    formMain_support.set_Tk_var()
    top = Toplevel1 (w)
    formMain_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font15 = "-family {DejaVu Sans} -size 10 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font16 = "-family {Ubuntu Condensed} -size 40 -weight bold "  \
            "-slant italic -underline 0 -overstrike 0"
        font17 = "-family {Ubuntu Condensed} -size 30 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font18 = "-family Ubuntu -size 10 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font20 = "-family {Trebuchet MS} -size 16 -weight bold -slant "  \
            "italic -underline 0 -overstrike 0"
        font21 = "-family {DejaVu Sans} -size 16 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("846x602+390+102")
        top.title("New Toplevel")
        top.configure(highlightcolor="black")

        self.frameTitlebar = tk.Frame(top)
        self.frameTitlebar.place(x=0, y=0, height=45, width=846)
        self.frameTitlebar.configure(relief='flat')
        self.frameTitlebar.configure(borderwidth="2")
        self.frameTitlebar.configure(background="#595959")
        self.frameTitlebar.configure(width=845)

        self.lblTitleBar = tk.Label(self.frameTitlebar)
        self.lblTitleBar.place(x=230, y=10,  height=29, width=386)
        self.lblTitleBar.configure(activebackground="#f9f9f9")
        self.lblTitleBar.configure(background="#595959")
        self.lblTitleBar.configure(font=font15)
        self.lblTitleBar.configure(foreground="#ffffff")
        self.lblTitleBar.configure(text='''Label''')
        self.lblTitleBar.configure(textvariable=formMain_support.Title)

        self.btnExit = tk.Button(self.frameTitlebar)
        self.btnExit.place(x=810, y=5,  height=29, width=29)
        self.btnExit.configure(activebackground="#393939")
        self.btnExit.configure(activeforeground="white")
        self.btnExit.configure(background="#595959")
        self.btnExit.configure(borderwidth="0")
        self.btnExit.configure(command=formMain_support.on_btnExit)
        self.btnExit.configure(font=font15)
        self.btnExit.configure(foreground="#ff1900")
        self.btnExit.configure(relief="flat")
        self.btnExit.configure(text='''X''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(x=0, y=45, height=559, width=846)
        self.Frame2.configure(relief='flat')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(background="#595959")
        self.Frame2.configure(width=845)

        self.TCombobox1 = ttk.Combobox(self.Frame2)
        self.TCombobox1.place(x=10, y=40, height=19, width=225)
        self.TCombobox1.configure(textvariable=formMain_support.ComboLocations)
        self.TCombobox1.configure(takefocus="")

        self.Label1 = tk.Label(self.Frame2)
        self.Label1.place(x=10, y=10,  height=19, width=225)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#595959")
        self.Label1.configure(font=font15)
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''Locations''')

        self.Label2 = tk.Label(self.Frame2)
        self.Label2.place(x=260, y=90,  height=69, width=196)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#595959")
        self.Label2.configure(font=font16)
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''109.7° F''')
        self.Label2.configure(textvariable=formMain_support.CurrentTemp)

        self.lblCurrentIcon = tk.Label(self.Frame2)
        self.lblCurrentIcon.place(x=200, y=95,  height=60, width=60)
        self.lblCurrentIcon.configure(activebackground="#f9f9f9")
        self.lblCurrentIcon.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/clear-day-55.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.lblCurrentIcon.configure(image=_img0)
        self.lblCurrentIcon.configure(text='''Label''')

        self.DIcon1 = tk.Label(self.Frame2)
        self.DIcon1.place(x=670, y=70,  height=60, width=60)
        self.DIcon1.configure(activebackground="#f9f9f9")
        self.DIcon1.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/clear-day-55.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.DIcon1.configure(image=_img1)
        self.DIcon1.configure(relief="sunken")
        self.DIcon1.configure(text='''Label''')

        self.TSeparator1 = ttk.Separator(self.Frame2)
        self.TSeparator1.place(x=660, y=0, height=540)
        self.TSeparator1.configure(orient="vertical")

        self.TSeparator2 = ttk.Separator(self.Frame2)
        self.TSeparator2.place(x=5, y=375, width=653)

        self.Label5 = tk.Label(self.Frame2)
        self.Label5.place(x=75, y=410,  height=55, width=55)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/partly-cloudy-day-55.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Label5.configure(image=_img2)
        self.Label5.configure(text='''Label''')

        self.Label6 = tk.Label(self.Frame2)
        self.Label6.place(x=185, y=410,  height=55, width=55)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/clear-night-55.png")
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.Label6.configure(image=_img3)
        self.Label6.configure(text='''Label''')

        self.Label7 = tk.Label(self.Frame2)
        self.Label7.place(x=295, y=410,  height=55, width=55)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/partly-cloudy-night-55.png")
        global _img4
        _img4 = tk.PhotoImage(file=photo_location)
        self.Label7.configure(image=_img4)
        self.Label7.configure(text='''Label''')

        self.Label8 = tk.Label(self.Frame2)
        self.Label8.place(x=405, y=410,  height=55, width=55)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/clear-day-55.png")
        global _img5
        _img5 = tk.PhotoImage(file=photo_location)
        self.Label8.configure(image=_img5)
        self.Label8.configure(text='''Label''')

        self.Label9 = tk.Label(self.Frame2)
        self.Label9.place(x=515, y=410,  height=55, width=55)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/partly-cloudy-day-55.png")
        global _img6
        _img6 = tk.PhotoImage(file=photo_location)
        self.Label9.configure(image=_img6)
        self.Label9.configure(text='''Label''')

        self.Label10 = tk.Label(self.Frame2)
        self.Label10.place(x=620, y=400,  height=119, width=36)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(background="#595959")
        self.Label10.configure(font=font17)
        self.Label10.configure(highlightbackground="#393939")
        self.Label10.configure(relief="groove")
        self.Label10.configure(text='''>''')

        self.lblH1Temp = tk.Label(self.Frame2)
        self.lblH1Temp.place(x=60, y=470,  height=19, width=76)
        self.lblH1Temp.configure(activebackground="#f9f9f9")
        self.lblH1Temp.configure(background="#595959")
        self.lblH1Temp.configure(font=font18)
        self.lblH1Temp.configure(foreground="#ffffff")
        self.lblH1Temp.configure(text='''101/100''')
        self.lblH1Temp.configure(textvariable=formMain_support.H1Temp)

        self.lblH1Hour = tk.Label(self.Frame2)
        self.lblH1Hour.place(x=60, y=490,  height=19, width=76)
        self.lblH1Hour.configure(activebackground="#f9f9f9")
        self.lblH1Hour.configure(background="#595959")
        self.lblH1Hour.configure(font=font18)
        self.lblH1Hour.configure(foreground="#ffffff")
        self.lblH1Hour.configure(text='''12:00P''')
        self.lblH1Hour.configure(textvariable=formMain_support.H1Hour)

        self.lblH1Temp_1 = tk.Label(self.Frame2)
        self.lblH1Temp_1.place(x=170, y=470,  height=19, width=76)
        self.lblH1Temp_1.configure(activebackground="#f9f9f9")
        self.lblH1Temp_1.configure(background="#595959")
        self.lblH1Temp_1.configure(font=font18)
        self.lblH1Temp_1.configure(foreground="#ffffff")
        self.lblH1Temp_1.configure(text='''101/100''')
        self.lblH1Temp_1.configure(textvariable=formMain_support.H2Temp)

        self.lblH1Temp_2 = tk.Label(self.Frame2)
        self.lblH1Temp_2.place(x=280, y=470,  height=19, width=76)
        self.lblH1Temp_2.configure(activebackground="#f9f9f9")
        self.lblH1Temp_2.configure(background="#595959")
        self.lblH1Temp_2.configure(font=font18)
        self.lblH1Temp_2.configure(foreground="#ffffff")
        self.lblH1Temp_2.configure(text='''101/100''')
        self.lblH1Temp_2.configure(textvariable=formMain_support.H3Temp)

        self.lblH1Temp_3 = tk.Label(self.Frame2)
        self.lblH1Temp_3.place(x=390, y=470,  height=19, width=76)
        self.lblH1Temp_3.configure(activebackground="#f9f9f9")
        self.lblH1Temp_3.configure(background="#595959")
        self.lblH1Temp_3.configure(font=font18)
        self.lblH1Temp_3.configure(foreground="#ffffff")
        self.lblH1Temp_3.configure(text='''101/100''')
        self.lblH1Temp_3.configure(textvariable=formMain_support.H4Temp)

        self.lblH1Temp_4 = tk.Label(self.Frame2)
        self.lblH1Temp_4.place(x=500, y=470,  height=19, width=76)
        self.lblH1Temp_4.configure(activebackground="#f9f9f9")
        self.lblH1Temp_4.configure(background="#595959")
        self.lblH1Temp_4.configure(font=font18)
        self.lblH1Temp_4.configure(foreground="#ffffff")
        self.lblH1Temp_4.configure(text='''101/100''')
        self.lblH1Temp_4.configure(textvariable=formMain_support.H5Temp)

        self.lblH1Hour_5 = tk.Label(self.Frame2)
        self.lblH1Hour_5.place(x=170, y=490,  height=19, width=76)
        self.lblH1Hour_5.configure(activebackground="#f9f9f9")
        self.lblH1Hour_5.configure(background="#595959")
        self.lblH1Hour_5.configure(font=font18)
        self.lblH1Hour_5.configure(foreground="#ffffff")
        self.lblH1Hour_5.configure(text='''12:00P''')
        self.lblH1Hour_5.configure(textvariable=formMain_support.H2Hour)

        self.lblH1Hour_6 = tk.Label(self.Frame2)
        self.lblH1Hour_6.place(x=280, y=490,  height=19, width=76)
        self.lblH1Hour_6.configure(activebackground="#f9f9f9")
        self.lblH1Hour_6.configure(background="#595959")
        self.lblH1Hour_6.configure(font=font18)
        self.lblH1Hour_6.configure(foreground="#ffffff")
        self.lblH1Hour_6.configure(text='''12:00P''')
        self.lblH1Hour_6.configure(textvariable=formMain_support.H3Hour)

        self.lblH1Hour_7 = tk.Label(self.Frame2)
        self.lblH1Hour_7.place(x=390, y=490,  height=19, width=76)
        self.lblH1Hour_7.configure(activebackground="#f9f9f9")
        self.lblH1Hour_7.configure(background="#595959")
        self.lblH1Hour_7.configure(font=font18)
        self.lblH1Hour_7.configure(foreground="#ffffff")
        self.lblH1Hour_7.configure(text='''12:00P''')
        self.lblH1Hour_7.configure(textvariable=formMain_support.H4Hour)

        self.lblH1Hour_8 = tk.Label(self.Frame2)
        self.lblH1Hour_8.place(x=500, y=490,  height=19, width=76)
        self.lblH1Hour_8.configure(activebackground="#f9f9f9")
        self.lblH1Hour_8.configure(background="#595959")
        self.lblH1Hour_8.configure(font=font18)
        self.lblH1Hour_8.configure(foreground="#ffffff")
        self.lblH1Hour_8.configure(text='''12:00P''')
        self.lblH1Hour_8.configure(textvariable=formMain_support.H5Hour)

        self.Label10_9 = tk.Label(self.Frame2)
        self.Label10_9.place(x=10, y=400,  height=119, width=36)
        self.Label10_9.configure(activebackground="#f9f9f9")
        self.Label10_9.configure(background="#595959")
        self.Label10_9.configure(font=font17)
        self.Label10_9.configure(highlightbackground="#393939")
        self.Label10_9.configure(text='''<''')

        self.lblWindPrompt = tk.Label(self.Frame2)
        self.lblWindPrompt.place(x=20, y=230,  height=19, width=196)
        self.lblWindPrompt.configure(activebackground="#f9f9f9")
        self.lblWindPrompt.configure(background="#595959")
        self.lblWindPrompt.configure(foreground="#ffffff")
        self.lblWindPrompt.configure(relief="groove")
        self.lblWindPrompt.configure(text='''Wind:''')

        self.lblHumidityPrompt = tk.Label(self.Frame2)
        self.lblHumidityPrompt.place(x=230, y=230,  height=19, width=143)
        self.lblHumidityPrompt.configure(activebackground="#f9f9f9")
        self.lblHumidityPrompt.configure(background="#595959")
        self.lblHumidityPrompt.configure(foreground="#ffffff")
        self.lblHumidityPrompt.configure(relief="groove")
        self.lblHumidityPrompt.configure(text='''Humidity:''')

        self.lblDewPointPrompt = tk.Label(self.Frame2)
        self.lblDewPointPrompt.place(x=390, y=230,  height=21, width=110)
        self.lblDewPointPrompt.configure(activebackground="#f9f9f9")
        self.lblDewPointPrompt.configure(background="#595959")
        self.lblDewPointPrompt.configure(foreground="#ffffff")
        self.lblDewPointPrompt.configure(relief="groove")
        self.lblDewPointPrompt.configure(text='''DewPt:''')

        self.lblUVIndexPrompt = tk.Label(self.Frame2)
        self.lblUVIndexPrompt.place(x=510, y=230,  height=19, width=116)
        self.lblUVIndexPrompt.configure(activebackground="#f9f9f9")
        self.lblUVIndexPrompt.configure(background="#595959")
        self.lblUVIndexPrompt.configure(foreground="#ffffff")
        self.lblUVIndexPrompt.configure(relief="groove")
        self.lblUVIndexPrompt.configure(text='''UV Index:''')

        self.lblVisibilityPrompt = tk.Label(self.Frame2)
        self.lblVisibilityPrompt.place(x=120, y=290,  height=19, width=156)
        self.lblVisibilityPrompt.configure(activebackground="#f9f9f9")
        self.lblVisibilityPrompt.configure(background="#595959")
        self.lblVisibilityPrompt.configure(foreground="#ffffff")
        self.lblVisibilityPrompt.configure(relief="groove")
        self.lblVisibilityPrompt.configure(text='''Visibility:''')

        self.lblPressurePrompt = tk.Label(self.Frame2)
        self.lblPressurePrompt.place(x=285, y=290,  height=21, width=144)
        self.lblPressurePrompt.configure(activebackground="#f9f9f9")
        self.lblPressurePrompt.configure(background="#595959")
        self.lblPressurePrompt.configure(foreground="#ffffff")
        self.lblPressurePrompt.configure(relief="groove")
        self.lblPressurePrompt.configure(text='''Pressure:''')

        self.lblWind = tk.Label(self.Frame2)
        self.lblWind.place(x=20, y=250,  height=19, width=196)
        self.lblWind.configure(activebackground="#f9f9f9")
        self.lblWind.configure(background="#595959")
        self.lblWind.configure(foreground="#ffffff")
        self.lblWind.configure(relief="groove")
        self.lblWind.configure(text='''Label''')
        self.lblWind.configure(textvariable=formMain_support.CurrentWind)

        self.Label16 = tk.Label(self.Frame2)
        self.Label16.place(x=230, y=250,  height=19, width=141)
        self.Label16.configure(activebackground="#f9f9f9")
        self.Label16.configure(background="#595959")
        self.Label16.configure(foreground="#ffffff")
        self.Label16.configure(relief="groove")
        self.Label16.configure(text='''40%''')
        self.Label16.configure(textvariable=formMain_support.CurrentHumidity)

        self.Label17 = tk.Label(self.Frame2)
        self.Label17.place(x=390, y=250,  height=19, width=110)
        self.Label17.configure(activebackground="#f9f9f9")
        self.Label17.configure(background="#595959")
        self.Label17.configure(foreground="#ffffff")
        self.Label17.configure(relief="groove")
        self.Label17.configure(text='''68''')
        self.Label17.configure(textvariable=formMain_support.CurrentDewPoint)

        self.Label18 = tk.Label(self.Frame2)
        self.Label18.place(x=510, y=250,  height=19, width=116)
        self.Label18.configure(activebackground="#f9f9f9")
        self.Label18.configure(background="#595959")
        self.Label18.configure(foreground="#ffffff")
        self.Label18.configure(relief="groove")
        self.Label18.configure(text='''11''')
        self.Label18.configure(textvariable=formMain_support.CurrentUVIndex)

        self.Label19 = tk.Label(self.Frame2)
        self.Label19.place(x=120, y=310,  height=19, width=156)
        self.Label19.configure(activebackground="#f9f9f9")
        self.Label19.configure(background="#595959")
        self.Label19.configure(foreground="#ffffff")
        self.Label19.configure(relief="groove")
        self.Label19.configure(text='''10+ mi''')
        self.Label19.configure(textvariable=formMain_support.CurrentVisibility)

        self.Label20 = tk.Label(self.Frame2)
        self.Label20.place(x=285, y=310,  height=19, width=144)
        self.Label20.configure(activebackground="#f9f9f9")
        self.Label20.configure(background="#595959")
        self.Label20.configure(foreground="#ffffff")
        self.Label20.configure(relief="groove")
        self.Label20.configure(text='''1014 mb''')
        self.Label20.configure(textvariable=formMain_support.CurrentPressure)

        self.TCombobox2 = ttk.Combobox(self.Frame2)
        self.TCombobox2.place(x=250, y=40, height=19, width=177)
        self.TCombobox2.configure(textvariable=formMain_support.ComboLanguage)
        self.TCombobox2.configure(takefocus="")

        self.Label1_1 = tk.Label(self.Frame2)
        self.Label1_1.place(x=240, y=10,  height=19, width=175)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(background="#595959")
        self.Label1_1.configure(font=font15)
        self.Label1_1.configure(foreground="#ffffff")
        self.Label1_1.configure(text='''Language''')

        self.Label1_2 = tk.Label(self.Frame2)
        self.Label1_2.place(x=450, y=10,  height=19, width=105)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(background="#595959")
        self.Label1_2.configure(font=font15)
        self.Label1_2.configure(foreground="#ffffff")
        self.Label1_2.configure(text='''Units''')

        self.TCombobox3 = ttk.Combobox(self.Frame2)
        self.TCombobox3.place(x=450, y=40, height=19, width=107)
        self.TCombobox3.configure(textvariable=formMain_support.ComboUnits)
        self.TCombobox3.configure(takefocus="")

        self.lblSummary = tk.Label(self.Frame2)
        self.lblSummary.place(x=20, y=180,  height=39, width=636)
        self.lblSummary.configure(activebackground="#f9f9f9")
        self.lblSummary.configure(background="#595959")
        self.lblSummary.configure(font=font15)
        self.lblSummary.configure(foreground="#ffffff")
        self.lblSummary.configure(text='''Mostly cloudy throughout the day.Label''')
        self.lblSummary.configure(textvariable=formMain_support.CurrentSummary)
        self.lblSummary.configure(width=636)
        tooltip_font = "-family {DejaVu Sans} -size 9"
        ToolTip(self.lblSummary, tooltip_font, '''550''', delay=0.5)

        self.Label3 = tk.Label(self.Frame2)
        self.Label3.place(x=140, y=160,  height=21, width=78)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#595959")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(text='''Feels Like:''')

        self.Label21 = tk.Label(self.Frame2)
        self.Label21.place(x=220, y=160,  height=19, width=46)
        self.Label21.configure(activebackground="#f9f9f9")
        self.Label21.configure(anchor='w')
        self.Label21.configure(background="#595959")
        self.Label21.configure(foreground="#ffffff")
        self.Label21.configure(text='''101o''')
        self.Label21.configure(textvariable=formMain_support.CurrentFeelsLike)

        self.Label21_2 = tk.Label(self.Frame2)
        self.Label21_2.place(x=300, y=160,  height=21, width=38)
        self.Label21_2.configure(activebackground="#f9f9f9")
        self.Label21_2.configure(background="#595959")
        self.Label21_2.configure(foreground="#ffffff")
        self.Label21_2.configure(text='''Low:''')

        self.Label22 = tk.Label(self.Frame2)
        self.Label22.place(x=350, y=160,  height=19, width=46)
        self.Label22.configure(activebackground="#f9f9f9")
        self.Label22.configure(anchor='w')
        self.Label22.configure(background="#595959")
        self.Label22.configure(foreground="#ffffff")
        self.Label22.configure(text='''74o''')
        self.Label22.configure(textvariable=formMain_support.LowTemp)

        self.Label23 = tk.Label(self.Frame2)
        self.Label23.place(x=430, y=160,  height=21, width=42)
        self.Label23.configure(activebackground="#f9f9f9")
        self.Label23.configure(background="#595959")
        self.Label23.configure(foreground="#ffffff")
        self.Label23.configure(text='''High:''')

        self.Label24 = tk.Label(self.Frame2)
        self.Label24.place(x=480, y=160,  height=19, width=46)
        self.Label24.configure(activebackground="#f9f9f9")
        self.Label24.configure(anchor='w')
        self.Label24.configure(background="#595959")
        self.Label24.configure(foreground="#ffffff")
        self.Label24.configure(text='''101o''')
        self.Label24.configure(textvariable=formMain_support.HighTemp)

        self.lblDataFrom = tk.Label(self.Frame2)
        self.lblDataFrom.place(x=20, y=340,  height=19, width=416)
        self.lblDataFrom.configure(activebackground="#f9f9f9")
        self.lblDataFrom.configure(anchor='w')
        self.lblDataFrom.configure(background="#595959")
        self.lblDataFrom.configure(foreground="#ffffff")
        self.lblDataFrom.configure(text='''Label''')
        self.lblDataFrom.configure(textvariable=formMain_support.DataFrom)
        tooltip_font = "-family {DejaVu Sans} -size 9"
        ToolTip(self.lblDataFrom, tooltip_font, ''' ''', delay=0.5)

        self.lblAlertIcon = tk.Label(self.Frame2)
        self.lblAlertIcon.place(x=130, y=100,  height=60, width=60)
        self.lblAlertIcon.configure(activebackground="#f9f9f9")
        self.lblAlertIcon.configure(background="#595959")
        self.lblAlertIcon.configure(cursor="shuttle")
        self.lblAlertIcon.configure(disabledforeground="#303030")
        self.lblAlertIcon.configure(state='disabled')
        self.lblAlertIcon.configure(text='''Label''')

        self.lblHourlyBlock = tk.Label(self.Frame2)
        self.lblHourlyBlock.place(x=200, y=380,  height=21, width=269)
        self.lblHourlyBlock.configure(activebackground="#f9f9f9")
        self.lblHourlyBlock.configure(background="#595959")
        self.lblHourlyBlock.configure(font=font15)
        self.lblHourlyBlock.configure(foreground="#ffffff")
        self.lblHourlyBlock.configure(text='''Hourly''')

        self.lblDailyBlock = tk.Label(self.Frame2)
        self.lblDailyBlock.place(x=690, y=0,  height=21, width=139)
        self.lblDailyBlock.configure(activebackground="#f9f9f9")
        self.lblDailyBlock.configure(background="#595959")
        self.lblDailyBlock.configure(font=font15)
        self.lblDailyBlock.configure(foreground="#ffffff")
        self.lblDailyBlock.configure(text='''Daily''')

        self.lblPoweredLink = tk.Label(self.Frame2)
        self.lblPoweredLink.place(x=390, y=520,  height=31, width=269)
        self.lblPoweredLink.configure(activebackground="#f9f9f9")
        self.lblPoweredLink.configure(background="#595959")
        self.lblPoweredLink.configure(cursor="shuttle")
        self.lblPoweredLink.configure(font=font20)
        self.lblPoweredLink.configure(foreground="#7a9eff")
        self.lblPoweredLink.configure(text='''Powered by Dark Sky''')

        self.TSeparator3 = ttk.Separator(self.Frame2)
        self.TSeparator3.place(x=660, y=25, width=180)

        self.lblPushDown = tk.Label(self.Frame2)
        self.lblPushDown.place(x=675, y=40,  height=21, width=150)
        self.lblPushDown.configure(activebackground="#f9f9f9")
        self.lblPushDown.configure(background="#595959")
        self.lblPushDown.configure(font=font21)
        self.lblPushDown.configure(foreground="#ffffff")
        self.lblPushDown.configure(relief="groove")
        self.lblPushDown.configure(text='''⏷''')

        self.lblPushUp = tk.Label(self.Frame2)
        self.lblPushUp.place(x=675, y=470,  height=21, width=150)
        self.lblPushUp.configure(activebackground="#f9f9f9")
        self.lblPushUp.configure(background="#595959")
        self.lblPushUp.configure(font=font21)
        self.lblPushUp.configure(foreground="#ffffff")
        self.lblPushUp.configure(relief="groove")
        self.lblPushUp.configure(text='''⏶''')

        self.lblDT1 = tk.Label(self.Frame2)
        self.lblDT1.place(x=735, y=70,  height=19, width=96)
        self.lblDT1.configure(activebackground="#f9f9f9")
        self.lblDT1.configure(background="#595959")
        self.lblDT1.configure(font=font18)
        self.lblDT1.configure(foreground="#ffffff")
        self.lblDT1.configure(relief="sunken")
        self.lblDT1.configure(text='''101/100''')
        self.lblDT1.configure(textvariable=formMain_support.DTemp1)

        self.lblDP1 = tk.Label(self.Frame2)
        self.lblDP1.place(x=735, y=90,  height=19, width=96)
        self.lblDP1.configure(activebackground="#f9f9f9")
        self.lblDP1.configure(background="#595959")
        self.lblDP1.configure(font=font18)
        self.lblDP1.configure(foreground="#ffffff")
        self.lblDP1.configure(relief="sunken")
        self.lblDP1.configure(text='''101/100''')
        self.lblDP1.configure(textvariable=formMain_support.DPrec1)

        self.lblDD1 = tk.Label(self.Frame2)
        self.lblDD1.place(x=735, y=110,  height=19, width=96)
        self.lblDD1.configure(activebackground="#f9f9f9")
        self.lblDD1.configure(background="#595959")
        self.lblDD1.configure(font=font18)
        self.lblDD1.configure(foreground="#ffffff")
        self.lblDD1.configure(relief="sunken")
        self.lblDD1.configure(text='''101/100''')
        self.lblDD1.configure(textvariable=formMain_support.DDay1)

        self.DIcon2 = tk.Label(self.Frame2)
        self.DIcon2.place(x=670, y=175,  height=60, width=60)
        self.DIcon2.configure(activebackground="#f9f9f9")
        self.DIcon2.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/clear-day-55.png")
        global _img7
        _img7 = tk.PhotoImage(file=photo_location)
        self.DIcon2.configure(image=_img7)
        self.DIcon2.configure(relief="sunken")
        self.DIcon2.configure(text='''Label''')

        self.DIcon3 = tk.Label(self.Frame2)
        self.DIcon3.place(x=670, y=275,  height=60, width=60)
        self.DIcon3.configure(activebackground="#f9f9f9")
        self.DIcon3.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/clear-day-55.png")
        global _img8
        _img8 = tk.PhotoImage(file=photo_location)
        self.DIcon3.configure(image=_img8)
        self.DIcon3.configure(relief="sunken")
        self.DIcon3.configure(text='''Label''')

        self.DIcon4 = tk.Label(self.Frame2)
        self.DIcon4.place(x=670, y=375,  height=60, width=60)
        self.DIcon4.configure(activebackground="#f9f9f9")
        self.DIcon4.configure(background="#595959")
        photo_location = os.path.join(prog_location,"./icons/clear-day-55.png")
        global _img9
        _img9 = tk.PhotoImage(file=photo_location)
        self.DIcon4.configure(image=_img9)
        self.DIcon4.configure(relief="sunken")
        self.DIcon4.configure(text='''Label''')

        self.lblDT2 = tk.Label(self.Frame2)
        self.lblDT2.place(x=735, y=175,  height=19, width=96)
        self.lblDT2.configure(activebackground="#f9f9f9")
        self.lblDT2.configure(background="#595959")
        self.lblDT2.configure(font=font18)
        self.lblDT2.configure(foreground="#ffffff")
        self.lblDT2.configure(relief="sunken")
        self.lblDT2.configure(text='''101/100''')
        self.lblDT2.configure(textvariable=formMain_support.DTemp2)

        self.lblDT3 = tk.Label(self.Frame2)
        self.lblDT3.place(x=735, y=275,  height=19, width=96)
        self.lblDT3.configure(activebackground="#f9f9f9")
        self.lblDT3.configure(background="#595959")
        self.lblDT3.configure(font=font18)
        self.lblDT3.configure(foreground="#ffffff")
        self.lblDT3.configure(relief="sunken")
        self.lblDT3.configure(text='''101/100''')
        self.lblDT3.configure(textvariable=formMain_support.DTemp3)

        self.lblDT4 = tk.Label(self.Frame2)
        self.lblDT4.place(x=735, y=375,  height=19, width=96)
        self.lblDT4.configure(activebackground="#f9f9f9")
        self.lblDT4.configure(background="#595959")
        self.lblDT4.configure(font=font18)
        self.lblDT4.configure(foreground="#ffffff")
        self.lblDT4.configure(relief="sunken")
        self.lblDT4.configure(text='''101/100''')
        self.lblDT4.configure(textvariable=formMain_support.DTemp4)

        self.lblDP2 = tk.Label(self.Frame2)
        self.lblDP2.place(x=735, y=195,  height=19, width=96)
        self.lblDP2.configure(activebackground="#f9f9f9")
        self.lblDP2.configure(background="#595959")
        self.lblDP2.configure(font=font18)
        self.lblDP2.configure(foreground="#ffffff")
        self.lblDP2.configure(relief="sunken")
        self.lblDP2.configure(text='''101/100''')
        self.lblDP2.configure(textvariable=formMain_support.DPrec2)

        self.lblDP3 = tk.Label(self.Frame2)
        self.lblDP3.place(x=735, y=295,  height=19, width=96)
        self.lblDP3.configure(activebackground="#f9f9f9")
        self.lblDP3.configure(background="#595959")
        self.lblDP3.configure(font=font18)
        self.lblDP3.configure(foreground="#ffffff")
        self.lblDP3.configure(relief="sunken")
        self.lblDP3.configure(text='''101/100''')
        self.lblDP3.configure(textvariable=formMain_support.DPrec3)

        self.lblDP4 = tk.Label(self.Frame2)
        self.lblDP4.place(x=735, y=395,  height=19, width=96)
        self.lblDP4.configure(activebackground="#f9f9f9")
        self.lblDP4.configure(background="#595959")
        self.lblDP4.configure(font=font18)
        self.lblDP4.configure(foreground="#ffffff")
        self.lblDP4.configure(relief="sunken")
        self.lblDP4.configure(text='''101/100''')
        self.lblDP4.configure(textvariable=formMain_support.DPrec4)

        self.lblDD2 = tk.Label(self.Frame2)
        self.lblDD2.place(x=735, y=215,  height=19, width=96)
        self.lblDD2.configure(activebackground="#f9f9f9")
        self.lblDD2.configure(background="#595959")
        self.lblDD2.configure(font=font18)
        self.lblDD2.configure(foreground="#ffffff")
        self.lblDD2.configure(relief="sunken")
        self.lblDD2.configure(text='''101/100''')
        self.lblDD2.configure(textvariable=formMain_support.DDay2)

        self.lblDD3 = tk.Label(self.Frame2)
        self.lblDD3.place(x=735, y=315,  height=19, width=96)
        self.lblDD3.configure(activebackground="#f9f9f9")
        self.lblDD3.configure(background="#595959")
        self.lblDD3.configure(font=font18)
        self.lblDD3.configure(foreground="#ffffff")
        self.lblDD3.configure(relief="sunken")
        self.lblDD3.configure(text='''101/100''')
        self.lblDD3.configure(textvariable=formMain_support.DDay3)

        self.lblDD4 = tk.Label(self.Frame2)
        self.lblDD4.place(x=735, y=415,  height=19, width=96)
        self.lblDD4.configure(activebackground="#f9f9f9")
        self.lblDD4.configure(background="#595959")
        self.lblDD4.configure(font=font18)
        self.lblDD4.configure(foreground="#ffffff")
        self.lblDD4.configure(relief="sunken")
        self.lblDD4.configure(text='''101/100''')
        self.lblDD4.configure(textvariable=formMain_support.DDay4)

# ======================================================
# Modified by Rozen to remove Tkinter import statements and to receive
# the font as an argument.
# ======================================================
# Found the original code at:
# http://code.activestate.com/recipes/576688-tooltip-for-tkinter/
# ======================================================

from time import time, localtime, strftime

class ToolTip(tk.Toplevel):
    """
    Provides a ToolTip widget for Tkinter.
    To apply a ToolTip to any Tkinter widget, simply pass the widget to the
    ToolTip constructor
    """
    def __init__(self, wdgt, tooltip_font, msg=None, msgFunc=None,
                 delay=1, follow=True):
        """
        Initialize the ToolTip

        Arguments:
          wdgt: The widget this ToolTip is assigned to
          tooltip_font: Font to be used
          msg:  A static string message assigned to the ToolTip
          msgFunc: A function that retrieves a string to use as the ToolTip text
          delay:   The delay in seconds before the ToolTip appears(may be float)
          follow:  If True, the ToolTip follows motion, otherwise hides
        """
        self.wdgt = wdgt
        # The parent of the ToolTip is the parent of the ToolTips widget
        self.parent = self.wdgt.master
        # Initalise the Toplevel
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        # Hide initially
        self.withdraw()
        # The ToolTip Toplevel should have no frame or title bar
        self.overrideredirect(True)

        # The msgVar will contain the text displayed by the ToolTip
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        # The text of the ToolTip is displayed in a Message widget
        tk.Message(self, textvariable=self.msgVar, bg='#FFFFDD',
                font=tooltip_font,
                aspect=1000).grid()

        # Add bindings to the widget.  This will NOT override
        # bindings that the widget already has
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')

    def spawn(self, event=None):
        """
        Spawn the ToolTip.  This simply makes the ToolTip eligible for display.
        Usually this is caused by entering the widget

        Arguments:
          event: The event that called this funciton
        """
        self.visible = 1
        # The after function takes a time argument in miliseconds
        self.after(int(self.delay * 1000), self.show)

    def show(self):
        """
        Displays the ToolTip if the time delay has been long enough
        """
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()

    def move(self, event):
        """
        Processes motion within the widget.
        Arguments:
          event: The event that called this function
        """
        self.lastMotion = time()
        # If the follow flag is not set, motion within the
        # widget will make the ToolTip disappear
        #
        if self.follow is False:
            self.withdraw()
            self.visible = 1

        # Offset the ToolTip 10x10 pixes southwest of the pointer
        self.geometry('+%i+%i' % (event.x_root+20, event.y_root-10))
        try:
            # Try to call the message function.  Will not change
            # the message if the message function is None or
            # the message function fails
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)

    def hide(self, event=None):
        """
        Hides the ToolTip.  Usually this is caused by leaving the widget
        Arguments:
          event: The event that called this function
        """
        self.visible = 0
        self.withdraw()

# ===========================================================
#                   End of Class ToolTip
# ===========================================================

if __name__ == '__main__':
    vp_start_gui()





