#############################################################################
# Generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#  Jul 28, 2019 08:53:04 PM CDT  platform: Linux
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

# from vTcl:image:dump_create_image_header
set proj_dir $::vTcl(proj_dir)
set proj_split  [file split $proj_dir]
set image_list { \
    clear_day_55_png ./icons/clear-day-55.png \
    clear_night_55_png ./icons/clear-night-55.png \
    partly_cloudy_day_55_png ./icons/partly-cloudy-day-55.png \
    partly_cloudy_night_55_png ./icons/partly-cloudy-night-55.png \
}
foreach {image image_file} $image_list {

    # from vTcl:image:dump_create_image
    set image_split [file split $image_file]
    set full_split [list {*}$proj_dir {*}$image_split]
    # from vTcl:image:dump_create_image_footer
    global proj_dir
    set full_file [join $full_split "/"]
    set full_file [file normalize $full_file]
    if {![file exists $full_file]} {
        set proj_dir [file normalize $proj_dir]
        set text \
"Image '$image' not found in $proj_dir.
Exiting PAGE."
        tk_messageBox -title Error -icon error -message $text
        stop
    }
    vTcl:image:create_new_image $full_file {} user {} $image
}

if {!$vTcl(borrow)} {

set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {DejaVu Sans Mono} -size 9"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
vTcl:font:add_font \
    "-family {Ubuntu Condensed} -size 40 -weight bold -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font16
vTcl:font:add_font \
    "-family {Ubuntu Condensed} -size 30 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font17
vTcl:font:add_font \
    "-family Ubuntu -size 10 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font18
vTcl:font:add_font \
    "-family {Trebuchet MS} -size 16 -weight bold -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font20
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 16 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font21


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}


proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 846x602+390+102
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1265 770
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -background {#595959} -height 45 -highlightcolor black \
        -width 845 
    vTcl:DefineAlias "$top.fra43" "frameTitlebar" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font15,object) \
        -foreground {#ffffff} -highlightcolor black -text Label \
        -textvariable Title 
    vTcl:DefineAlias "$site_3_0.lab45" "lblTitleBar" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but46 \
        -activebackground {#393939} -activeforeground black \
        -background {#595959} -borderwidth 0 -command on_btnExit \
        -font $::vTcl(fonts,vTcl:font15,object) -foreground {#ff1900} \
        -highlightcolor black -relief flat -text X 
    vTcl:DefineAlias "$site_3_0.but46" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 234 -y 10 -width 386 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 810 -y 7 -width 29 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra43
    frame $top.fra44 \
        -borderwidth 2 -background {#595959} -height 555 \
        -highlightcolor black -width 845 
    vTcl:DefineAlias "$top.fra44" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    ttk::combobox $site_3_0.tCo47 \
        -font TkTextFont -textvariable ComboLocations -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo47" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font15,object) \
        -foreground {#ffffff} -highlightcolor black -text Locations 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#595959} -font $::vTcl(fonts,vTcl:font16,object) \
        -foreground {#ffffff} -highlightcolor black -text {109.7° F} \
        -textvariable CurrentTemp 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image clear_day_55_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab50" "lblCurrentIcon" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image clear_day_55_png -relief sunken \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab51" "DIcon1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab51
    ttk::separator $site_3_0.tSe52 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe52" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe53
    vTcl:DefineAlias "$site_3_0.tSe53" "TSeparator2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image partly_cloudy_day_55_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab54" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image clear_night_55_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab55" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image partly_cloudy_night_55_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab56" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image clear_day_55_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab57" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image partly_cloudy_day_55_png -text Label 
    vTcl:DefineAlias "$site_3_0.lab58" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font17,object) \
        -foreground {#000000} -highlightbackground {#393939} \
        -highlightcolor black -relief groove -text > 
    vTcl:DefineAlias "$site_3_0.lab59" "Label10" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 101/100 \
        -textvariable H1Temp 
    vTcl:DefineAlias "$site_3_0.lab60" "lblH1Temp" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 12:00P \
        -textvariable H1Hour 
    vTcl:DefineAlias "$site_3_0.lab62" "lblH1Hour" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 101/100 \
        -textvariable H2Temp 
    vTcl:DefineAlias "$site_3_0.lab42" "lblH1Temp_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 101/100 \
        -textvariable H3Temp 
    vTcl:DefineAlias "$site_3_0.lab43" "lblH1Temp_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 101/100 \
        -textvariable H4Temp 
    vTcl:DefineAlias "$site_3_0.lab44" "lblH1Temp_3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 101/100 \
        -textvariable H5Temp 
    vTcl:DefineAlias "$site_3_0.lab45" "lblH1Temp_4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 12:00P \
        -textvariable H2Hour 
    vTcl:DefineAlias "$site_3_0.lab46" "lblH1Hour_5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 12:00P \
        -textvariable H3Hour 
    vTcl:DefineAlias "$site_3_0.lab47" "lblH1Hour_6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 12:00P \
        -textvariable H4Hour 
    vTcl:DefineAlias "$site_3_0.lab52" "lblH1Hour_7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -text 12:00P \
        -textvariable H5Hour 
    vTcl:DefineAlias "$site_3_0.lab53" "lblH1Hour_8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font17,object) \
        -foreground {#000000} -highlightbackground {#393939} \
        -highlightcolor black -text < 
    vTcl:DefineAlias "$site_3_0.lab61" "Label10_9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text Wind: 
    vTcl:DefineAlias "$site_3_0.lab63" "lblWindPrompt" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text Humidity: 
    vTcl:DefineAlias "$site_3_0.lab64" "lblHumidityPrompt" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text DewPt: 
    vTcl:DefineAlias "$site_3_0.lab65" "lblDewPointPrompt" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text {UV Index:} 
    vTcl:DefineAlias "$site_3_0.lab67" "lblUVIndexPrompt" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text Visibility: 
    vTcl:DefineAlias "$site_3_0.lab68" "lblVisibilityPrompt" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text Pressure: 
    vTcl:DefineAlias "$site_3_0.lab69" "lblPressurePrompt" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab70 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text Label \
        -textvariable CurrentWind 
    vTcl:DefineAlias "$site_3_0.lab70" "lblWind" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text 40% \
        -textvariable CurrentHumidity 
    vTcl:DefineAlias "$site_3_0.lab71" "Label16" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab72 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text 68 \
        -textvariable CurrentDewPoint 
    vTcl:DefineAlias "$site_3_0.lab72" "Label17" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab73 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text 11 \
        -textvariable CurrentUVIndex 
    vTcl:DefineAlias "$site_3_0.lab73" "Label18" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text {10+ mi} \
        -textvariable CurrentVisibility 
    vTcl:DefineAlias "$site_3_0.lab74" "Label19" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab75 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -relief groove -text {1014 mb} \
        -textvariable CurrentPressure 
    vTcl:DefineAlias "$site_3_0.lab75" "Label20" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo76 \
        -font TkTextFont -textvariable ComboLanguage -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo76" "TCombobox2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab77 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font15,object) \
        -foreground {#ffffff} -highlightcolor black -text Language 
    vTcl:DefineAlias "$site_3_0.lab77" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab78 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font15,object) \
        -foreground {#ffffff} -highlightcolor black -text Units 
    vTcl:DefineAlias "$site_3_0.lab78" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo79 \
        -font TkTextFont -textvariable ComboUnits -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo79" "TCombobox3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab80 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font15,object) \
        -foreground {#ffffff} -highlightcolor black \
        -text {Mostly cloudy throughout the day.Label} \
        -textvariable CurrentSummary 
    vTcl:DefineAlias "$site_3_0.lab80" "lblSummary" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab80 <<SetBalloon>> {
        set ::vTcl::balloon::%W {550}
    }
    label $site_3_0.lab81 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text {Feels Like: } 
    vTcl:DefineAlias "$site_3_0.lab81" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab83 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text 101o -textvariable CurrentFeelsLike 
    vTcl:DefineAlias "$site_3_0.lab83" "Label21" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab84 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text {Low: } 
    vTcl:DefineAlias "$site_3_0.lab84" "Label21_2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab85 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text 74o -textvariable LowTemp 
    vTcl:DefineAlias "$site_3_0.lab85" "Label22" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab86 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text {High: } 
    vTcl:DefineAlias "$site_3_0.lab86" "Label23" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab87 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text 101o -textvariable HighTemp 
    vTcl:DefineAlias "$site_3_0.lab87" "Label24" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab88 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#595959} -font TkDefaultFont -foreground {#ffffff} \
        -highlightcolor black -text Label -textvariable DataFrom 
    vTcl:DefineAlias "$site_3_0.lab88" "lblDataFrom" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.lab88 <<SetBalloon>> {
        set ::vTcl::balloon::%W { }
    }
    label $site_3_0.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -cursor shuttle -disabledforeground {#303030} \
        -font TkDefaultFont -foreground {#000000} -highlightcolor black \
        -state disabled -text Label 
    vTcl:DefineAlias "$site_3_0.lab66" "lblAlertIcon" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font15,object) \
        -foreground {#ffffff} -highlightcolor black -text Hourly 
    vTcl:DefineAlias "$site_3_0.lab76" "lblHourlyBlock" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab79 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font15,object) \
        -foreground {#ffffff} -highlightcolor black -text Daily 
    vTcl:DefineAlias "$site_3_0.lab79" "lblDailyBlock" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab82 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -cursor shuttle \
        -font $::vTcl(fonts,vTcl:font20,object) -foreground {#7a9eff} \
        -highlightcolor black -text {Powered by Dark Sky} 
    vTcl:DefineAlias "$site_3_0.lab82" "lblPoweredLink" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe42
    vTcl:DefineAlias "$site_3_0.tSe42" "TSeparator3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab89 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font21,object) \
        -foreground {#ffffff} -highlightcolor black -relief groove -text ⏷ 
    vTcl:DefineAlias "$site_3_0.lab89" "lblPushDown" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab90 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font21,object) \
        -foreground {#ffffff} -highlightcolor black -relief groove -text ⏶ 
    vTcl:DefineAlias "$site_3_0.lab90" "lblPushUp" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab91 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DTemp1 
    vTcl:DefineAlias "$site_3_0.lab91" "lblDT1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab91
    label $site_3_0.lab92 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DPrec1 
    vTcl:DefineAlias "$site_3_0.lab92" "lblDP1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab92
    label $site_3_0.lab93 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DDay1 
    vTcl:DefineAlias "$site_3_0.lab93" "lblDD1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab93
    label $site_3_0.lab94 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image clear_day_55_png -relief sunken \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab94" "DIcon2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab94
    label $site_3_0.lab95 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image clear_day_55_png -relief sunken \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab95" "DIcon3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab95
    label $site_3_0.lab96 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -image clear_day_55_png -relief sunken \
        -text Label 
    vTcl:DefineAlias "$site_3_0.lab96" "DIcon4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab96
    label $site_3_0.lab99 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DTemp2 
    vTcl:DefineAlias "$site_3_0.lab99" "lblDT2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab99
    label $site_3_0.lab100 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DTemp3 
    vTcl:DefineAlias "$site_3_0.lab100" "lblDT3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab100
    label $site_3_0.lab101 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DTemp4 
    vTcl:DefineAlias "$site_3_0.lab101" "lblDT4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab101
    label $site_3_0.lab102 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DPrec2 
    vTcl:DefineAlias "$site_3_0.lab102" "lblDP2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab102
    label $site_3_0.lab103 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DPrec3 
    vTcl:DefineAlias "$site_3_0.lab103" "lblDP3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab103
    label $site_3_0.lab104 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DPrec4 
    vTcl:DefineAlias "$site_3_0.lab104" "lblDP4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab104
    label $site_3_0.lab105 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DDay2 
    vTcl:DefineAlias "$site_3_0.lab105" "lblDD2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab105
    label $site_3_0.lab106 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DDay3 
    vTcl:DefineAlias "$site_3_0.lab106" "lblDD3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab106
    label $site_3_0.lab107 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#595959} -font $::vTcl(fonts,vTcl:font18,object) \
        -foreground {#ffffff} -highlightcolor black -relief sunken \
        -text 101/100 -textvariable DDay4 
    vTcl:DefineAlias "$site_3_0.lab107" "lblDD4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab107
    place $site_3_0.tCo47 \
        -in $site_3_0 -x 10 -y 40 -width 225 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 10 -width 225 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 260 -y 90 -width 196 -relwidth 0 -height 69 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 200 -y 98 -width 60 -relwidth 0 -height 60 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 670 -y 70 -width 60 -relwidth 0 -height 60 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tSe52 \
        -in $site_3_0 -x 661 -y 2 -width 2 -height 540 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe53 \
        -in $site_3_0 -x 8 -y 375 -width 653 -relwidth 0 -height 2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 76 -y 410 -width 55 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 185 -y 410 -width 55 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 295 -y 410 -width 55 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 405 -y 410 -width 55 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 515 -y 410 -width 55 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 620 -y 400 -width 36 -relwidth 0 -height 119 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 60 -y 470 -width 76 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 60 -y 490 -width 76 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab42 \
        -in $site_3_0 -x 170 -y 470 -width 76 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 280 -y 470 -width 76 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 390 -y 470 -width 76 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 500 -y 470 -width 76 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 170 -y 490 -width 76 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 280 -y 490 -width 76 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 390 -y 490 -width 76 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 500 -y 490 -width 76 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 13 -y 400 -width 36 -height 119 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 20 -y 230 -width 196 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 230 -y 230 -width 143 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 390 -y 230 -width 110 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 510 -y 230 -width 116 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 120 -y 290 -width 156 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 288 -y 290 -width 144 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 20 -y 251 -width 196 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 230 -y 250 -width 141 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 390 -y 250 -width 110 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 510 -y 250 -width 116 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 120 -y 313 -width 156 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 288 -y 313 -width 144 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo76 \
        -in $site_3_0 -x 250 -y 40 -width 177 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 240 -y 10 -width 175 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 450 -y 10 -width 105 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo79 \
        -in $site_3_0 -x 450 -y 40 -width 107 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab80 \
        -in $site_3_0 -x 20 -y 180 -width 636 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 140 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 220 -y 160 -width 46 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab84 \
        -in $site_3_0 -x 300 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 350 -y 160 -width 46 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab86 \
        -in $site_3_0 -x 430 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.lab87 \
        -in $site_3_0 -x 480 -y 160 -width 46 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 20 -y 343 -width 416 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 130 -y 100 -width 60 -height 60 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 200 -y 380 -width 269 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 690 -y 2 -width 139 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 390 -y 520 -width 269 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tSe42 \
        -in $site_3_0 -x 662 -y 29 -width 180 -height 2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab89 \
        -in $site_3_0 -x 678 -y 40 -width 150 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 678 -y 470 -width 150 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab91 \
        -in $site_3_0 -x 735 -y 70 -width 96 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab92 \
        -in $site_3_0 -x 735 -y 90 -width 96 -relwidth 0 -height 19 \
        -anchor nw -bordermode ignore 
    place $site_3_0.lab93 \
        -in $site_3_0 -x 735 -y 110 -width 96 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab94 \
        -in $site_3_0 -x 670 -y 175 -width 60 -height 60 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab95 \
        -in $site_3_0 -x 670 -y 275 -width 60 -height 60 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab96 \
        -in $site_3_0 -x 670 -y 375 -width 60 -height 60 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab99 \
        -in $site_3_0 -x 735 -y 175 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab100 \
        -in $site_3_0 -x 735 -y 275 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab101 \
        -in $site_3_0 -x 735 -y 375 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab102 \
        -in $site_3_0 -x 735 -y 195 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab103 \
        -in $site_3_0 -x 735 -y 295 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab104 \
        -in $site_3_0 -x 735 -y 395 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab105 \
        -in $site_3_0 -x 735 -y 215 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab106 \
        -in $site_3_0 -x 735 -y 315 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab107 \
        -in $site_3_0 -x 735 -y 415 -width 96 -height 19 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.fra44
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 0 -y 0 -width 846 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 0 -y 45 -width 846 -relwidth 0 -height 559 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

